# Generated by Django 3.2.6 on 2021-08-10 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=253)),
                ('extension', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('accountCreatedOn', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=2000)),
                ('discoveryDate', models.DateTimeField()),
                ('lastUpdated', models.DateTimeField()),
                ('discoveredBy', models.ForeignKey(default='Anonymous', on_delete=django.db.models.deletion.SET_DEFAULT, to='mySite.user')),
                ('domainID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mySite.domain')),
            ],
        ),
    ]
