# Generated by Django 3.2.6 on 2021-08-10 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='discoveryDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 10, 18, 42, 8, 854442)),
            preserve_default=False,
        ),
    ]
