# Generated by Django 3.2.6 on 2021-08-10 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mySite', '0002_domain_discoverydate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endpoint',
            old_name='domainID',
            new_name='domain',
        ),
    ]
